### ISSUE TITLE
Error: Request body larger than maxBodyLength limit

### ISSUE THREAD

**Issue by hassan-maavan** [Musiio-AI/tagging-sample#12]
I want to know the max file size limit so that I can apply on my code.

**Comment by abhinavk1** [comment]
We have a file upload limit of 100 mb

**Comment by hassan-maavan** [comment]
But, I'm getting this error for the 40mb .mp3 file.

**Comment by abhinavk1** [comment]
According to Axios documentation the max body size is set at 2000 bytes, you'll have to override that. I tested the API with Postman using a 40 mb file and it worked.
https://github.com/axios/axios

**Comment by hassan-maavan** [comment]
Thanks, @abhinavk1
